version: '3.7'
services:
    blog:
        container_name: ${CODEUSER}_blog
        image: frank30941/myblog:latest
        restart: unless-stopped
        networks:
            - worknet
        volumes:
            - "workspace:/config/"
        environment:
            - PUID=${UID}
            - PGID=${GID}
            - TZ=Asia/Taipei
        deploy:
            replicas: 2
            labels:
                - traefik.enable=true
                - "traefik.http.routers.blog-http.rule=${BLOGDOMAINNAME}"
                - traefik.http.routers.blog-http.entrypoints=http
                - "traefik.http.routers.blog-https.rule=${BLOGDOMAINNAME}"
                - traefik.http.routers.blog-https.entrypoints=https
                - traefik.http.routers.blog-http.middlewares=blog-redirect
                - traefik.http.middlewares.blog-redirect.redirectscheme.scheme=https
                - traefik.http.routers.blog-https.middlewares=blog-redirectregex
                - "traefik.http.middlewares.blog-redirectregex.redirectregex.regex=${REDIRECTREGEX_FROM}(.*)"
                - "traefik.http.middlewares.blog-redirectregex.redirectregex.replacement=${REDIRECTREGEX_TO}$${1}"
                - "traefik.http.routers.blog-https.tls.certresolver=${CODEUSER}"
                - "traefik.http.services.blog-service.loadbalancer.server.port=80"
volumes:
    workspace:
        external: true
        name: workspace
networks:
    worknet:
        external: true
        name: worknet
