version: '3.7'
services:
    blog:
        container_name: ${CODEUSER}_blog
        image: frank30941/myblog
        restart: unless-stopped
        networks:
            - netself
        volumes:
            - "v_blog:/config/"
        environment:
#            - "HUGO_BASEURL=${BLOGDOMAINNAME}"
            - TZ=Asia/Taipei
        labels:
            - traefik.enable=true
            - "traefik.http.routers.blog-http.rule=${BLOGDOMAINNAME}"
            - traefik.http.routers.blog-http.entrypoints=http
            - "traefik.http.routers.blog-https.rule=${BLOGDOMAINNAME}"
            - traefik.http.routers.blog-https.entrypoints=https
            - traefik.http.routers.blog-http.middlewares=blog-redirect
            - traefik.http.middlewares.blog-redirect.redirectscheme.scheme=https
            - "traefik.http.routers.blog-https.tls.certresolver=${CODEUSER}"
volumes:
    v_blog:
        name: ${CODEUSER}_cs
networks:
    netself:
        name: ${CODEUSER}
